SSCS-10978: initial implementation of send letter functionality
hmcts/sscs-evidence-share pull request #1480
Opened 2023-02-22 17:04 UTC by AndreiTrushkov

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10978

### Change description ###
initial implementation of send letter functionality for generic letter

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-27 09:18 UTC, jarekPierchala approved these changes

2023-02-27 09:38 UTC, hajam09 approved these changes

2023-04-21 13:38 UTC, jarekPierchala requested changes

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueGenericLetterHandler.java
> +        //Optional.of(UUID.randomUUID());
remove that comment

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueGenericLetterHandler.java
> +        long id = callback.getCaseDetails().getId();
caseDetailsId as a name please

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueGenericLetterHandler.java
> +        // blank page??
if its something to be done leave TODO comment rather then what you have got now

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueGenericLetterHandler.java
> +        return FurtherEvidenceLetterType.OTHER_PARTY_LETTER;
```suggestion
       boolean hasRepresentative = otherParty.hasRepresentative() && entityId.equals(otherParty.getRep().getId());
       return hasRepresentative ? FurtherEvidenceLetterType.OTHER_PARTY_REP_LETTER :FurtherEvidenceLetterType.OTHER_PARTY_LETTER;
```

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueGenericLetterHandler.java
> +
no need for that empty line

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/service/CoverLetterService.java
> +
no need for empty line

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/GenericLetterPlaceholderService.java
> +
no need for empty line

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/GenericLetterPlaceholderService.java
> +        }
```suggestion
         var addressPlaceHolders = new HashMap<String, Object>();
        String[] lines = lines(address);
        String[] addressConstants = {LETTER_ADDRESS_LINE_1, LETTER_ADDRESS_LINE_2, LETTER_ADDRESS_LINE_3, LETTER_ADDRESS_LINE_4, LETTER_ADDRESS_POSTCODE};

        for (int i = 0; i <= lines.length; i++){
            addressPlaceHolders.put(addressConstants[i], truncateAddressLine(defaultToEmptyStringIfNull(lines[i])));
        }
``` 

Try this out Andrei

2023-04-21 13:38 UTC, jarekPierchala commented on src/main/java/uk/gov/hmcts/reform/sscs/service/placeholders/PlaceholderUtility.java
> +                    && isValidName(otherParty.getValue().getName())) {
otherParty.getValue() to seperate var

2023-04-21 13:54 UTC, AndreiTrushkov commented on src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/IssueGenericLetterHandler.java
> +        //Optional.of(UUID.randomUUID());
done

2023-04-21 14:20 UTC, jarekPierchala approved these changes

2023-04-26 11:27 UTC, jarekPierchala approved these changes

2023-04-26 13:25 UTC, merged